# Generated by Django 2.2.7 on 2019-11-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_field',
            new_name='question',
        ),
    ]
